version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
  haproxy:
    image: haproxy:latest
    ports:
      - "443:443"
    environment:
      - BACKEND_SERVERS=server1:80,server2:80
  server1:
    image: nginx:latest
    ports:
      - "80"
  server2:
    image: nginx:latest
    ports:
      - "80"

