version: "3"
services:
  web:
    build: .
    ports:
      - "8080:80"
  haproxy:
    image: haproxy:latest
    ports:
      - "443:8080"
    volumes:
    - /path/to/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg -D    
    environment:
      - BACKEND_SERVERS=server1:80,server2:80
  server1:
    image: nginx:latest
    ports:
      - "80"
  server2:
    image: nginx:latest
    ports:
      - "80"