version: '3'
services:
  webapp1:
    build: .
    networks:
      - webapp
  webapp2:
    build: .
    networks:
      - webapp
  haproxy:
    image: haproxy:latest
    ports:
      - "80:80"
      - "443:443"
    networks:
      - webapp
    depends_on:
      - webapp1
      - webapp2
networks:
  webapp:
    driver: bridge
